### ISSUE TITLE
Difference between Ram and Minimap2

### ISSUE THREAD

**Issue by shelkmike** [jmaricb/RAM#1]
If I understand correctly, the main idea of Ram is to create paf files which are smaller than paf files created by Minimap2. However, I couldn't find any details about algorithmic differences between Ram and Minimap2. Could you please describe them here as detailed as possible?

**Comment by rvaser** [comment]
Hello Mikhail,
Ram was initially almost identical to minimap**1**. There might be some code changes (non-algorithmic) which yield small differences in overlap positions. From `v2.2.0` we are rescuing a portion of filtered high-occurrence minimizers, just like in minimap2 `v2.19`. To sum up, Ram uses minimap1 chaining with minimap2 minimizer rescue.

Best regards,
Robert

P.S. There is also an option to subsample minimizers with minhash to decrease the execution time, which is not present in both minimaps.

**Comment by shelkmike** [comment]
Thank you. In your PhD thesis you wrote 
> "Finalizing our assembler we wanted to omit hefty disc requirements present in large genomes. With that purpose in mind we transformed Minimap to a C++ library with some slight modifications. We called it Ram and it is available at https://github.com/lbcb-sci/ram"

What is the algorithmic difference between Ram and Minimap that helps Ram to use less disc space?

**Comment by rvaser** [comment]
We modified the API only, no changes to the algorithm were made to decrease its memory consumption. Ram takes in compressed sequences (2bits per base, the same as minimizers) instead of default DNA strings (Raven stores reads in that form directly from file).

I also forgot to mention in my last answer that Ram compares sequences by ids (rank in file), instead of names like Minimap1/2, to avoid symmetric overlaps in all-vs-all mode (i.e. compute only A->B or B->A).

P.S. A way to reduce memory in Ram is to use minhash option as only a fraction of minimizers is stored/used.

**Comment by shelkmike** [comment]
Thank you for the answer
